# Generated by Django 5.0.dev20230322100140 on 2023-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='modified',
            field=models.DateField(null=True),
        ),
    ]
