# Generated by Django 5.0.dev20230322100140 on 2023-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
